---
- name: System setup
  hosts: all
  remote_user: root
  roles:
    - system

- name: BookStack setup
  hosts: all
  remote_user: freebsd
  roles:
    - bookstack

- name: System reboot
  hosts: all
  remote_user: root
  roles:
    - reboot
